config/routes.rb
Rails.application.routes.draw do

  resources :cashes

  resources :games

  resources :itineraries

  resources :relationships

  post '/rate' => 'rater#create', :as => 'rate'

  ActiveAdmin.routes(self)

  root "static_pages#home"
  get '/landing_page' => "static_pages#home", :as => "landing_page"

  resources :comments, :except =>[:index, :show]

  get "/auth/twitter", :as => "signin"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :stakes

  resources :tournaments

  resources :tours

  resources :users, :only => [:show, :index]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role? :admin
        can

    else
        user.role? :super_admin
         can :manage, :all
    elsif
        user.role? :user
        can :create, Stake
        can :read, Stake
        can :update, Stake do |stake|
            stake.try(:user) ==
        can :delete, Stake

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cash.rb
class Cash < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  resourcify
  include PublicActivity::Model
  #tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :stake

  belongs_to :user

  validates :user, :presence => true
  validates :content, :presence => true

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :investor_user, class_name: "User", foreign_key: 'investor_id'
  belongs_to :investment_user, class_name: "User", foreign_key:'investment_id'

  validates :investor_id, presence: true
  validates :investment_id, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/stake.rb
class Stake < ActiveRecord::Base
  include PublicActivity::Model
  #tracked owner: ->(controller, model) { controller && controller.current_user }

  validates :tour_id, presence: true
  validates :tournament_id, presence: true
  validates :amount_of_shares, numericality: { only_integer: true }

  belongs_to :user
  belongs_to :tour
  belongs_to :tournament

  has_many :comments

end

app/models/tour.rb
class Tour < ActiveRecord::Base
resourcify
validates :name, presence: true
has_many :tournaments

mount_uploader :image, ImageUploader
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
resourcify
validates :event, presence: true
validates :start_time, presence: true
validates :start_date, presence: true
validates :buy_in, numericality: true
validates :event_length, presence: true
validates :tour_id, presence: true

  belongs_to :tour
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates_presence_of :uid, :provider
  has_many :cashes
  has_many :comments
  has_many :stakes
  has_many :tours
  has_many :tournaments
  has_many :investor_relationships, class_name: "Relationship",foreign_key: 'investor_id'
  has_many :investment_relationships, class_name: "Relationship",foreign_key: 'investment_id'
  has_many :itineraries
  has_many :games

  ratyrate_rateable 'integrity'

  ratyrate_rater

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["name"]
      user.screen_name = auth["info"]["nickname"]
      user.image_url = auth["info"]["image"]
      user.location = auth["info"]["location"]
      # user = User.find(1)
      # user.add_role :user
    end
  end

   # user = User.find(2)
   # user.add_role :admin

   # user = User.find(3)
   # user.add_role :super_admin

   def investors
    relationships = self.investment_relationships
    users = []

    relationships.each do |relationship|
      users << relationship.investor_user
    end
    return users
  end

  def investments
    relationships = self.investor_relationships
    users = []

    relationships.each do |relationship|
      users << relationship.investment_user
    end
    return users
  end


  def self.client
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = "Rails.application.secrets['TWITTER_API_KEY']"
      config.consumer_secret     = "Rails.application.secrets['TWITTER_SECRET_KEY']"
    end
  end

  def self.user_tweets
  @client.user_timeline("gem")

  end
end

app/controllers/cashes_controller.rb
class CashesController < InheritedResources::Base

  private

    def cash_params
      params.require(:cash).permit(:user_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def user_signed_in?
  !!session[:user_id]
end

def authenticate_user!
 redirect_to root_url unless user_signed_in?
end
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stakes_helper.rb
module StakesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/cashes/_form.html.erb
<%= form_for(@cash) do |f| %>
  <% if @cash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cash.errors.count, "error") %> prohibited this cash from being saved:</h2>

      <ul>
      <% @cash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cashes/edit.html.erb
<h1>Editing Cash</h1>

<%= render 'form' %>

<%= link_to 'Show', @cash %> |
<%= link_to 'Back', cashes_path %>

app/views/cashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cashes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cashes.each do |cash| %>
      <tr>
        <td><%= cash.user_id %></td>
        <td><%= cash.content %></td>
        <td><%= link_to 'Show', cash %></td>
        <td><%= link_to 'Edit', edit_cash_path(cash) %></td>
        <td><%= link_to 'Destroy', cash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cash', new_cash_path %>

app/views/cashes/new.html.erb
<h1>New Cash</h1>

<%= render 'form' %>

<%= link_to 'Back', cashes_path %>

app/views/cashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cash.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @cash.content %>
</p>

<%= link_to 'Edit', edit_cash_path(@cash) %> |
<%= link_to 'Back', cashes_path %>