config/routes.rb
Rails.application.routes.draw do

  resources :cashes

  resources :games

  resources :itineraries

  resources :relationships

  post '/rate' => 'rater#create', :as => 'rate'

  ActiveAdmin.routes(self)

  root "static_pages#home"
  get '/landing_page' => "static_pages#home", :as => "landing_page"

  resources :comments, :except =>[:index, :show]

  get "/auth/twitter", :as => "signin"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :stakes

  resources :tournaments

  resources :tours

  resources :users, :only => [:show, :index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  resourcify
  include PublicActivity::Model
  #tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :stake

  belongs_to :user

  validates :user, :presence => true
  validates :content, :presence => true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :current_user_must_be_owner, only: [:edit, :update, :destroy]
before_action :authenticate

 def current_user_must_be_owner
    if current_user != @comment.user
      redirect_to :back
    end
  end
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
     respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @comment.create_activity :create, owner: current_user
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :stake_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id='comment_<%= comment.id %>' class="media">
  <div class="media-left">
    <%= image_tag comment.user.image_url %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= comment.user.username %></h4>

    <%= comment.content %><br>

  <small class="data-object">
    <%= time_ago_in_words(comment.created_at) %> ago
    <% if current_user == comment.user %>
    <%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-default btn-xs" %>
    <%= link_to 'Delete', comment_url(comment), method: :delete, data: { confirm: "Do you really want to delete this?" }, class: "btn btn-default btn-xs", :remote => true  %>
    <% end %>
  </small>
  </div>
</li>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :placeholder => "Add a comment", class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stake_id %><br>
    <%= f.number_field :stake_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= comment.id %>').slideUp();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>